Adding Camel Language Support for Emacs
camel-tooling/camel-lsp-client-emacs pull request #4
Opened 2022-06-01 15:35 UTC by Navyashree0923

2022-06-01 15:38 UTC, Navyashree0923 commented
I did something wrong and I wasn't able to see the changes in the previous pull request. So, I have created a new Pull Request. Please review it

2022-06-02 08:34 UTC, apupier requested changes

2022-06-02 08:34 UTC, apupier commented on README.md
> +## prerequisites
```suggestion
# Prerequisites
```

2022-06-02 08:34 UTC, apupier commented on README.md
> +```
Would be nice to add something like:
Then you can enjoy editing capabilities of Camel URI. For instance by calling completion with Ctrl+Alt+i in the uri attribute value.

2022-06-02 08:34 UTC, apupier commented on README.md
> +```lisp
```suggestion
```xml
```

this one is xml code, not lisp

2022-06-02 08:34 UTC, apupier commented on README.md
> +Code completion for Camel LS with XML LS
```suggestion
## This is a client implementation of the Apache Camel Language Server Protocol for Emacs
Link for Apache Camel Language Server 


# Text Editing capabilities of Camel URI with Camel XML DSL

For instance, code completion for Camel XML Dsl. The capabilities are based on the [Camel Language Server](https://github.com/camel-tooling/camel-language-server/).
```

2022-06-02 08:34 UTC, apupier commented on README.md
> +## How to configure Emacs
```suggestion
# How to configure Emacs
```

2022-06-02 10:44 UTC, Navyashree0923 commented
I have updated as per the comments, please review it.

2022-06-02 12:07 UTC, apupier approved these changes

2022-06-02 14:29 UTC, merged